// <auto-generated />
namespace TurnipTheBeetMKE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class quickupdatetoFMID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(quickupdatetoFMID));
        
        string IMigrationMetadata.Id
        {
            get { return "201610180506193_quick update to FM ID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
